//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.13 at 06:34:55 AM CET 
//


package de.dwpbank.xgen.test.coboltransformer.datadef;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="Len" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.Flags" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.Format" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.FormatType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.Length" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.Repeat" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.Type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VarLen" type="{http://www.w3.org/2001/XMLSchema}string" />
 *      <!-- Added a new parameter for holding the value of this field, based on the cobol file -->
 *       &lt;attribute name="Value" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Field")
public class Field {

    @XmlAttribute(name = "Len")
    protected String len;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Sized.Flags")
    protected String sizedFlags;
    @XmlAttribute(name = "Sized.Format", required = true)
    protected String sizedFormat;
    @XmlAttribute(name = "Sized.FormatType", required = true)
    protected String sizedFormatType;
    @XmlAttribute(name = "Sized.Length", required = true)
    protected String sizedLength;
    @XmlAttribute(name = "Sized.Repeat", required = true)
    protected String sizedRepeat;
    @XmlAttribute(name = "Sized.Type", required = true)
    protected String sizedType;
    @XmlAttribute(name = "Type", required = true)
    protected String type;
    @XmlAttribute(name = "VarLen")
    protected String varLen;
    @XmlAttribute(name = "value")
    private String value;

    /**
     * Gets the value of the len property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLen() {
        return len;
    }

    /**
     * Sets the value of the len property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLen(String value) {
        this.len = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sizedFlags property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedFlags() {
        return sizedFlags;
    }

    /**
     * Sets the value of the sizedFlags property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedFlags(String value) {
        this.sizedFlags = value;
    }

    /**
     * Gets the value of the sizedFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedFormat() {
        return sizedFormat;
    }

    /**
     * Sets the value of the sizedFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedFormat(String value) {
        this.sizedFormat = value;
    }

    /**
     * Gets the value of the sizedFormatType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedFormatType() {
        return sizedFormatType;
    }

    /**
     * Sets the value of the sizedFormatType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedFormatType(String value) {
        this.sizedFormatType = value;
    }

    /**
     * Gets the value of the sizedLength property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedLength() {
        return sizedLength;
    }

    /**
     * Sets the value of the sizedLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedLength(String value) {
        this.sizedLength = value;
    }

    /**
     * Gets the value of the sizedRepeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedRepeat() {
        return sizedRepeat;
    }

    /**
     * Sets the value of the sizedRepeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedRepeat(String value) {
        this.sizedRepeat = value;
    }

    /**
     * Gets the value of the sizedType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedType() {
        return sizedType;
    }

    /**
     * Sets the value of the sizedType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedType(String value) {
        this.sizedType = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the varLen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVarLen() {
        return varLen;
    }

    /**
     * Sets the value of the varLen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVarLen(String value) {
        this.varLen = value;
    }

    @Override
    public String toString() {
        return "Field{" + "len=" + len + ", name=" + name + ", sizedFlags=" + sizedFlags + ", sizedFormat=" + sizedFormat + ", sizedFormatType=" + sizedFormatType + ", sizedLength=" + sizedLength + ", sizedRepeat=" + sizedRepeat + ", sizedType=" + sizedType + ", type=" + type + ", varLen=" + varLen + '}';
    }

    /**
     * @return the value
     */
    public String getValue() {
        return value;
    }

    /**
     * @param value the value to set
     */
    public void setValue(String value) {
        this.value = value;
    }

}
