//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.13 at 06:34:55 AM CET 
//


package de.dwpbank.xgen.test.coboltransformer.datadef;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Field" maxOccurs="unbounded"/>
 *         &lt;element ref="{}Group"/>
 *       &lt;/sequence>
 *       &lt;attribute name="Sized.DefaultSign" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.EncDouble" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.EncFloat" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.EncInt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.EncNum" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.EncReal" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.EncString" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.EncUInt" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.EncZoned" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.SignEncoding" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "field",
    "group"
})
@XmlRootElement(name = "Fields")
public class Fields {

    @XmlElement(name = "Field", required = true)
    protected List<Field> field;
    @XmlElement(name = "Group", required = true)
    protected Group group;
    @XmlAttribute(name = "Sized.DefaultSign", required = true)
    protected String sizedDefaultSign;
    @XmlAttribute(name = "Sized.EncDouble", required = true)
    protected String sizedEncDouble;
    @XmlAttribute(name = "Sized.EncFloat", required = true)
    protected String sizedEncFloat;
    @XmlAttribute(name = "Sized.EncInt", required = true)
    protected String sizedEncInt;
    @XmlAttribute(name = "Sized.EncNum", required = true)
    protected String sizedEncNum;
    @XmlAttribute(name = "Sized.EncReal", required = true)
    protected String sizedEncReal;
    @XmlAttribute(name = "Sized.EncString", required = true)
    protected String sizedEncString;
    @XmlAttribute(name = "Sized.EncUInt", required = true)
    protected String sizedEncUInt;
    @XmlAttribute(name = "Sized.EncZoned", required = true)
    protected String sizedEncZoned;
    @XmlAttribute(name = "Sized.SignEncoding", required = true)
    protected String sizedSignEncoding;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getField() {
        if (field == null) {
            field = new ArrayList<Field>();
        }
        return this.field;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link Group }
     *     
     */
    public Group getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link Group }
     *     
     */
    public void setGroup(Group value) {
        this.group = value;
    }

    /**
     * Gets the value of the sizedDefaultSign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedDefaultSign() {
        return sizedDefaultSign;
    }

    /**
     * Sets the value of the sizedDefaultSign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedDefaultSign(String value) {
        this.sizedDefaultSign = value;
    }

    /**
     * Gets the value of the sizedEncDouble property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedEncDouble() {
        return sizedEncDouble;
    }

    /**
     * Sets the value of the sizedEncDouble property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedEncDouble(String value) {
        this.sizedEncDouble = value;
    }

    /**
     * Gets the value of the sizedEncFloat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedEncFloat() {
        return sizedEncFloat;
    }

    /**
     * Sets the value of the sizedEncFloat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedEncFloat(String value) {
        this.sizedEncFloat = value;
    }

    /**
     * Gets the value of the sizedEncInt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedEncInt() {
        return sizedEncInt;
    }

    /**
     * Sets the value of the sizedEncInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedEncInt(String value) {
        this.sizedEncInt = value;
    }

    /**
     * Gets the value of the sizedEncNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedEncNum() {
        return sizedEncNum;
    }

    /**
     * Sets the value of the sizedEncNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedEncNum(String value) {
        this.sizedEncNum = value;
    }

    /**
     * Gets the value of the sizedEncReal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedEncReal() {
        return sizedEncReal;
    }

    /**
     * Sets the value of the sizedEncReal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedEncReal(String value) {
        this.sizedEncReal = value;
    }

    /**
     * Gets the value of the sizedEncString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedEncString() {
        return sizedEncString;
    }

    /**
     * Sets the value of the sizedEncString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedEncString(String value) {
        this.sizedEncString = value;
    }

    /**
     * Gets the value of the sizedEncUInt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedEncUInt() {
        return sizedEncUInt;
    }

    /**
     * Sets the value of the sizedEncUInt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedEncUInt(String value) {
        this.sizedEncUInt = value;
    }

    /**
     * Gets the value of the sizedEncZoned property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedEncZoned() {
        return sizedEncZoned;
    }

    /**
     * Sets the value of the sizedEncZoned property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedEncZoned(String value) {
        this.sizedEncZoned = value;
    }

    /**
     * Gets the value of the sizedSignEncoding property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedSignEncoding() {
        return sizedSignEncoding;
    }

    /**
     * Sets the value of the sizedSignEncoding property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedSignEncoding(String value) {
        this.sizedSignEncoding = value;
    }

    @Override
    public String toString() {
        return "Fields{" + "field=" + field + ", group=" + group + ", sizedDefaultSign=" + sizedDefaultSign + ", sizedEncDouble=" + sizedEncDouble + ", sizedEncFloat=" + sizedEncFloat + ", sizedEncInt=" + sizedEncInt + ", sizedEncNum=" + sizedEncNum + ", sizedEncReal=" + sizedEncReal + ", sizedEncString=" + sizedEncString + ", sizedEncUInt=" + sizedEncUInt + ", sizedEncZoned=" + sizedEncZoned + ", sizedSignEncoding=" + sizedSignEncoding + '}';
    }

}
