//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.13 at 06:34:55 AM CET 
//


package de.dwpbank.xgen.test.coboltransformer.datadef;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element ref="{}Field"/>
 *         &lt;element ref="{}Group"/>
 *       &lt;/choice>
 *       &lt;attribute name="Max" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Min" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Sized.Repeat" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "fieldOrGroup"
})
@XmlRootElement(name = "Group")
public class Group {

    @XmlElements({
        @XmlElement(name = "Field", type = Field.class),
        @XmlElement(name = "Group", type = Group.class)
    })
    protected List<Object> fieldOrGroup;
    @XmlAttribute(name = "Max")
    protected String max;
    @XmlAttribute(name = "Min", required = true)
    protected String min;
    @XmlAttribute(name = "Name", required = true)
    protected String name;
    @XmlAttribute(name = "Sized.Repeat", required = true)
    protected String sizedRepeat;

    /**
     * Gets the value of the fieldOrGroup property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldOrGroup property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldOrGroup().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * {@link Group }
     * 
     * 
     */
    public List<Object> getFieldOrGroup() {
        if (fieldOrGroup == null) {
            fieldOrGroup = new ArrayList<Object>();
        }
        return this.fieldOrGroup;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMax(String value) {
        this.max = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMin(String value) {
        this.min = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the sizedRepeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSizedRepeat() {
        return sizedRepeat;
    }

    /**
     * Sets the value of the sizedRepeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSizedRepeat(String value) {
        this.sizedRepeat = value;
    }

    @Override
    public String toString() {
        return "Group{" + "fieldOrGroup=" + fieldOrGroup + ", max=" + max + ", min=" + min + ", name=" + name + ", sizedRepeat=" + sizedRepeat + '}';
    }

}
